# IS605 Assignment 13
Paul Garaud


### Analytical problems and solutions


#### Integrate

1. $$\int{sin(x)cos(x)}dx = \frac{1}{2}sin^2(x) + C$$
2. $$\int{x^2e^x}dx = x^2e^x - \int{2xe^x}dx = x^2e^x - (2xe^x - \int{2e^x}dx) = x^2e^x - 2xe^x + 2e^x + C$$


#### Differentiate

1. $$\frac{d}{dx}(xcos(x)) = cos(x) + x(-sin(x)) = cos(x) - xsin(x)$$
2. $$\frac{d}{dx}e^{x^4} = 4x^3e^{x^4}$$

### Programming

Write a program to compute the approximate derivative of $f(x) = x^3 + 2x^2$ at any value of $x$.

```{r d}
equation1 <- function(x) {
  return(x^3 + 2*x^2)
}

derivate <- function(eq, x) {
  delta <- 0.00000001
  f.x <- eq(x)
  f.a <- eq(x + delta)
  return((f.a - f.x) / delta)
}

# test cases
# analytic solution: 3x^2 + 4x

# expect:
# x = -1: -1
# x = 0: 0
# x = 1: 7

for (c in -1:1) {
  print(round(derivate(equation1, c), 0))
}
```

Write a program to compute the approximate area under the curve for the function $3x^2 + 4x$ in the domain $x = [1, 3]$.

```{r i}
equation2 <- function(x) {
  return(3*x^2 + 4*x)
}

integrate1 <- function(eq, lbound, ubound) {
  
  # create bins
  delta <- 0.00001
  bins <- seq(from = lbound, to = ubound - delta, by = delta)
  
  # sum area for each bin
  return(sum(sapply(bins, function(x) {return(eq(x) * delta)})))
}

# test cases
# analytic solution: (3)^3 + 2(3)^2 - 3 = 42

print(integrate1(equation2, 1, 3), 0)
```